---
- name: restart apache2
  service: >
    name=apache2
    state=restarted
    enabled=yes
  when: ansible_os_family == 'Debian'

- name: restart apache2
  service: >
    name=httpd
    state=started
    enabled=yes
  when: ansible_os_family == 'RedHat'
